version: '3'

services:
  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: # reemplaza /homne/diego/ por tu carpeta de usuario
      - "/home/diego/ftp/data:/home/usuario/"
      - "/home/diego/ftp/passwd:/etc/pure-ftpd/passwd"
    environment:
      PUBLICHOST: "192.168.1.250"
      FTP_USER_NAME: usuario
      FTP_USER_PASS: loquesea
      FTP_USER_HOME: /home/usuario
    restart: always
